package scanner;

public enum ExitCode {
    TOO_MANY_FAILED_SCANS,
    WRONG_PARAM_DEF,
    WRONG_PARAM_EXCL,
    INVALID_PATH,
    EMPTY_FOLDER,
    FILE_RENAMED_INCORRECTLY,
    RES_FOLDER_CREATION_FAILED,
    INVALID_SCAN_RESULT,
    SUCCESS,
    INVALID_FIRST_FILE,
    MORE_ANGLES_REQUIRED,
    FILE_READING_ISSUE
}
