name: Release BarcodeImageProcessor

on:
  push:
    tags:
      - v*
  
  workflow_dispatch:

jobs:
  build-installer-job:
    name: 'Build Win64 Installer'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: 'Set up JDK 15'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 15
          java-package: jdk+fx
      - name: 'Grant execute permission for Gradle'
        run: chmod +x gradlew
      - name: 'Build with Gradle'
        run: ./gradlew jpackage
      - name: 'Release Win64 Installer'
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          title: Release ${{github.ref}}
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: /build/jpackage-installer/*.msi
